package es.upm.dit.isst.model;

public enum Comunidades {
	ANDALUCÍA, ARAGÓN, ASTURIAS, BALEARES, CANARIAS, CANTABRIA, CASTILLALAMANCHA, CASTILLAYLEÓN, CATALUÑA, CEUTA, EXTREMADURA, GALICIA, LARIOJA, MADRID, MELILLA, MURCIA, NAVARRA, PAÍSVASCO, VALENCIA
}
