package es.upm.dit.isst.model;

public enum Comunidades {
	ANDALUCIA, ARAGON, ASTURIAS, BALEARES, CANARIAS, CANTABRIA, CASTILLALAMANCHA, CASTILLAYLEÓN, CATALUÑA, EXTREMADURA, GALICIA, LARIOJA, MADRID, MURCIA, NAVARRA, PAÍSVASCO, VALENCIA
}
